package slime.message.title;

import { Point2D } from slime.message.base;

enum TitleButtonEnum: uint16 {
    Minimize = 1,
    MaxRestore,
    Close,
}

struct TitleButtonClick {
    buttonType: TitleButtonEnum;
    points: Point2D[][];
}
